### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by wangxin1233** [Joker316701882/Deep-Image-Matting#37]
hello!
when I run the code :python test.py --alpha=./test_data/alpha/1.png --rgb=./test_data/RGB/1.png
always appear the follow error:
![image](https://user-images.githubusercontent.com/44840625/50446849-29841100-0952-11e9-82ad-b69f4f3689b5.png)
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "test.py", line 16, in main
    saver.restore(sess,tf.train.latest_checkpoint('./model'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1557, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
could you help me how to solve it?  thank you!

**Comment by VoyagerIII** [comment]
You haven't download the pre-trained model. And the pre-trained model can't be reached anymore.  so sad.

**Comment by wuzb19951013** [comment]
oh, bad news
